version = 1

[[annotations]]
path = ["go.mod", "go.sum", ".envrc", "flake.lock", ".editorconfig"]
SPDX-FileCopyrightText = "NONE"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = ["scripts/shaka.txt"]
SPDX-FileCopyrightText = "NONE"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = ["app/.env.example"]
SPDX-FileCopyrightText = "2025 BROKE DA EAR LLC <https://brokedaear.com>"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = ["*.proto"]
SPDX-FileCopyrightText = "2025 BROKE DA EAR LLC <https://brokedaear.com>"
SPDX-License-Identifier = "Apache-2.0"
