# SPDX-FileCopyrightText: 2025 BROKE DA EAR LLC <https://brokedaear.com>
#
# SPDX-License-Identifier: Apache-2.0
services:
  postgres:
    image: postgres:17-alpine
    container_name: brokedaear_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: brokedaear_shop
      POSTGRES_USER: brokedaear
      POSTGRES_PASSWORD: dev_password_change_in_production
    ports:
      - "5432:5432"
    volumes:
      - ./01-schema.sql:/docker-entrypoint-initdb.d/01-schema.sql:ro
      - ./02-test-seed-data.sql:/docker-entrypoint-initdb.d/02-seed-data.sql:ro
      - ./03-schema-load-valid.sh:/docker-entrypoint-initdb.d/03-load-seed.sh:ro
      - ./data/postgres:/var/lib/postgresql/data
      - ./data/backups:/backups
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U brokedaear -d brokedaear_shop"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - brokedaear_network
  redis:
    image: redis:7-alpine
    container_name: brokedaear_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - brokedaear_network
networks:
  brokedaear_network:
    driver: bridge
